CREATE TABLE CURRENCY
   (
   ID NUMBER(20,0),
	 FROM_CURRENCY_CODE VARCHAR2(20),
	 TO_CURRENCY_CODE VARCHAR2(20),
	 CONVERSION_RATE NUMBER(10, 3),
	 CONVERSION_DATE DATE
	 );

CREATE SEQUENCE CURRENCY_SEQ INCREMENT BY 1 START WITH 1;

INSERT INTO CURRENCY (ID,FROM_CURRENCY_CODE,TO_CURRENCY_CODE,CONVERSION_RATE,CONVERSION_DATE)
VALUES (CURRENCY_SEQ.nextval, 'EUR', 'INR', '75.24', sysdate);
INSERT INTO CURRENCY (ID,FROM_CURRENCY_CODE,TO_CURRENCY_CODE,CONVERSION_RATE,CONVERSION_DATE)
VALUES (CURRENCY_SEQ.nextval, 'EUR', 'INR', '75.24', sysdate - 1);